---

          - name: Create the directory for Docker compose
            file:
                    path: "{{ ansible_env.HOME }}/dawn"
                    state: directory
                    mode: '0755'

          - name: Copy the environment file
            template:
                    src: ".env"
                    dest: "{{ ansible_env.HOME }}/dawn/.env"
                    owner: "{{ ansible_env.USER }}"
                    group: "{{ ansible_env.USER }}"
                    mode: '0644'

          - name: Create the directory tree for Docker volumes
            file:
                    path: "{{ ansible_env.HOME }}/dawn_docker_volumes/{{ item }}"
                    state: directory
                    mode: '0755'
            loop: [ 'db_data', 'wordpress_data', 'nginx_data', 'ssh-proxy_data', 'ftp_data' ]

          - name: Copy the Nginx Configuration
            template:
                    src: "nginx.conf.j2"
                    dest: "{{ ansible_env.HOME }}/dawn_docker_volumes/nginx_data/nginx.conf"
                    owner: "{{ ansible_env.USER }}"
                    group: "{{ ansible_env.USER }}"
                    mode: '0644'


          - name: Copy the Docker Compose file over
            template:
                    src: "docker-compose.yml.j2"
                    dest: "{{ ansible_env.HOME }}/dawn/docker-compose.yml"
                    owner: "{{ ansible_env.USER }}"
                    group: "{{ ansible_env.USER }}"
                    mode: '0644'

          - name: Run Docker Compose
            raw: "cd $HOME/dawn; sudo docker-compose up -d"
