---

# TODO: Parameterize this for SSH-proxy as well?
- name: Pull the code of our Django app
  git:
    repo: "{{ django_app_repository }}"
    dest: "{{ ansible_env.HOME }}/{{ app_name }}"
    # TODO: Parameter for this.
    version: production

- name: Build the image of our Django app.
  # TODO: Parameter for where the Dockerfile is located, and from where the image is built
  raw: "docker build -t {{ app_name }} -f {{ ansible_env.HOME }}/{{ app_name }}/docker/Dockerfile {{ ansible_env.HOME }}/{{ app_name }}"
  ignore_errors: yes
 
- name: Clean up the code of our app
  file:
    path: "{{ ansible_env.HOME }}/{{ app_name }}"
    state: absent
